import BannerImage from "@/components/BannerImage";
import Header from "@/components/Header";
import Tracker from "@/components/Tracker";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>HabitBoost</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <BannerImage />
        <Tracker />
      </main>
    </>
  );
}
